"""
全局黑板模块导出

其他模块只需从此处导入，无需关心内部文件结构
"""

from .base_blackboard import BaseSubBlackboard
from .exceptions import BlackboardException, StatusUpdateError, SubBoardNotRegisteredError, TaskNotExistError
from .execution_blackboard import ExecutionBlackboard, execution_blackboard
from .global_blackboard import GlobalBlackboard, global_blackboard
from .knowledge_blackboard import KnowledgeBlackboard, knowledge_blackboard
from .memory_blackboard import MemoryBlackboard, memory_blackboard
from .schema import (
    ArtifactVerificationResult,
    AuditResultState,
    BusinessContextState,
    BusinessDocumentState,
    DebugAttemptRecord,
    DynamicRequestRuntimeState,
    DynamicRequestState,
    DynamicResumeOverlay,
    DynamicTraceEventState,
    ExecutionData,
    ExecutionStrategy,
    GeneratorManifest,
    GlobalStatus,
    HistoricalSkillMatchState,
    InputMountState,
    KnowledgeData,
    KnowledgeSnapshotMetadataState,
    KnowledgeSnapshotState,
    MemoryCacheHintState,
    MemoryData,
    NodeCheckpointState,
    NodeOutputPatchState,
    ReplayCaseState,
    RuntimeMetadataState,
    SkillAuthorizationState,
    SkillMetadataState,
    SkillPayloadState,
    SkillPromotionState,
    SkillProvenanceState,
    SkillRecommendedState,
    SkillUsageState,
    SkillValidationState,
    StaticEvidenceBundle,
    StaticProgramSpec,
    StaticRepairPlan,
    StructuredDatasetState,
    TaskGlobalState,
    TaskMemorySummaryState,
    WorkspacePreferenceState,
)
from .strict_state import build_strict_state_report

__all__ = [
    "BaseSubBlackboard",
    "ArtifactVerificationResult",
    "AuditResultState",
    "BusinessContextState",
    "BusinessDocumentState",
    "DebugAttemptRecord",
    "DynamicResumeOverlay",
    "DynamicRequestRuntimeState",
    "DynamicRequestState",
    "DynamicTraceEventState",
    "ExecutionStrategy",
    "GeneratorManifest",
    "GlobalStatus",
    "HistoricalSkillMatchState",
    "InputMountState",
    "KnowledgeSnapshotMetadataState",
    "StructuredDatasetState",
    "KnowledgeSnapshotState",
    "MemoryCacheHintState",
    "TaskMemorySummaryState",
    "WorkspacePreferenceState",
    "NodeOutputPatchState",
    "NodeCheckpointState",
    "ReplayCaseState",
    "RuntimeMetadataState",
    "StaticEvidenceBundle",
    "StaticProgramSpec",
    "StaticRepairPlan",
    "SkillAuthorizationState",
    "SkillMetadataState",
    "SkillPromotionState",
    "SkillProvenanceState",
    "SkillPayloadState",
    "SkillRecommendedState",
    "SkillUsageState",
    "SkillValidationState",
    "TaskGlobalState",
    "ExecutionData",
    "KnowledgeData",
    "MemoryData",
    "execution_blackboard",
    "ExecutionBlackboard",
    "knowledge_blackboard",
    "KnowledgeBlackboard",
    "memory_blackboard",
    "MemoryBlackboard",
    "build_strict_state_report",
    "TaskNotExistError",
    "BlackboardException",
    "SubBoardNotRegisteredError",
    "StatusUpdateError",
    "global_blackboard",
    "GlobalBlackboard",
]
